Update docs version as part of releaseprep

diff --git a/misc/generatedocs b/misc/generatedocs
--- a/misc/generatedocs
+++ b/misc/generatedocs
@@ -25,6 +25,24 @@
 # configuration script generated by Autoconf, you may include it under
 # the same distribution terms that you use for the rest of that program.
 
+show_usage() {
+        echo "Usage: `basename $0` [-v version]"
+        echo ""
+        echo "  -h, --help - Print this help and exit."
+        echo "  -v, --ver  - Update document version string."
+        exit 1
+}
+
+do_ver=0
+if test "x${1}" = "x-v" || test "x${1}" = "x--ver"; then
+        do_ver=1
+        if test "x${2}" = "x"; then
+                show_usage
+        fi
+        ver=$2
+fi
+
+
 BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 echo "*** Searching for pandoc..."
@@ -54,7 +72,22 @@ else
   echo "Not found. Sphinx can be found at http://www.sphinx-doc.org or via apt-get install python-sphinx. Exiting..."
   exit 1
 fi
-  
+
+
+if [ $do_ver -eq 1 ]; then
+  echo "*** Updating docs to version ${ver}..."
+  sed -e "s:version = '.*':version = '${ver}':" \
+      -e "s:release = '.*':release = '${ver}'": doc/sphinx_source/conf.py > doc/sphinx_source/conf.py_
+  if grep "version = '${ver}'" doc/sphinx_source/conf.py_ && grep "release = '${ver}'" doc/sphinx_source/conf.py_; then
+    mv doc/sphinx_source/conf.py_ doc/sphinx_source/conf.py
+    echo "Updated."
+  else
+    echo "Documentation version update failed. Aborting..."
+    exit 1
+  fi
+fi
+
+
 mkdir -p tmpdocs
 echo "*** Generating plaintext docs..."
 for i in $( find $BASEDIR/../doc/sphinx_source/ -type f -name "*.rst" ); do
