configure_makefile_fix3 patch

diff --git a/misc/modconfig b/misc/modconfig
--- a/misc/modconfig
+++ b/misc/modconfig
@@ -19,12 +19,13 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 
-# $Id: modconfig,v 1.2 2000/03/06 18:54:08 fabian Exp $
+# $Id: modconfig,v 1.3 2000/03/22 00:42:56 fabian Exp $
 
 
 mc_pn=`echo $0 | sed -e 's/^.*\///'`
 mc_top_srcdir=
 mc_srcdir=
+mc_bindir=.
 
 mc_flag_quiet=no
 mc_flag_onlynew=no
@@ -46,6 +47,13 @@ while true; do
 	--srcdir)
 		shift
 		mc_srcdir=${1}
+	;;
+	--bindir=*)
+		mc_bindir=`echo ${1} | sed -e 's/^--bindir=//'`
+	;;
+	--bindir)
+		shift
+		mc_bindir=${1}
 	;;
 	--quiet|-q)
 		mc_flag_quiet=yes
@@ -94,17 +102,18 @@ fi
 #
 
 #  List of all selected modules (including the `.mod' at the end)
-mc_fmodules=${mc_top_srcdir}/.modules
+mc_fmodules=${mc_bindir}/.modules
 
 #  List of all modules we have detected so far.
-mc_fknownmods=${mc_top_srcdir}/.known_modules
+mc_fknownmods=${mc_bindir}/.known_modules
 
 #  List of modules disabled by default
 mc_fdisabledmods=${mc_top_srcdir}/disabled_modules
 
 mc_mod_dir=${mc_srcdir}/mod
 
-mc_fMakefile=${mc_mod_dir}/Makefile
+mc_mod_bin_dir=${mc_bindir}/src/mod
+mc_fMakefile=${mc_mod_bin_dir}/Makefile
 
 mc_fstatic_h=${mc_mod_dir}/static.h
 
@@ -168,10 +177,12 @@ Commands:
     help                 Displays this information.
     detect-modules       Find all available modules.
     modules-still-exist  Check wether all known modules still exist.
+    eggautoconf          Recreate the configure scripts in every module dir.
 
 Options:
     --top_srcdir=DIR     Top directory         (At least one of these two
     --srcdir=DIR         Source directory       directories MUST be supplied.)
+    --bindir=DIR         Binary directory
     --quiet [-q]         Quiet mode. Only show errors.
 
 Options specific to the \`configure' command:
@@ -253,7 +264,7 @@ xdetect-modules)
 				mc_new_mod_state=enabled
 			else
 				#  Was it configured before?
-				if (grep "^${mc_mod}.mod\$" ${mc_fmodules} 1>&7 2>&1); then
+				if (grep "^${mc_mod}.mod\$" ${mc_fknownmods} 1>&7 2>&1); then
 					:
 				else
 					mc_new_mod_state=enabled
@@ -675,6 +686,33 @@ EOF
 		echo "failed!" 1>&6
 		exit 1
 	fi
+;;
+xeggautoconf)
+#
+#  Recreate the eggdrop specific configure scripts for every module.
+#
+
+	#  Detect available modules
+	mc_mods=`echo ${mc_mod_dir}/*.mod`
+
+	#  Error out if we have no available modules
+	if test "${mc_mods}" = "echo ${mc_mod_dir}/*.mod"; then
+		echo "${mc_pn}: error: no modules found." 1>&2
+		exit 1
+	fi
+
+	#  Loop through each available module
+	for mc_modd in ${mc_mods}; do
+		#  Skip modules without their own configure script.
+		if test ! -r "${mc_modd}/configure.in"; then
+			continue
+		fi
+
+		#  Remove directory information from name
+		mc_mod=`echo ${mc_modd} | sed -e 's/.*\///'`
+		echo "creating configure for module \`${mc_mod}'."
+		(cd ${mc_modd} && ../eggautoconf)
+	done
 ;;
 *)
 	if test "x${mc_cmd}" = x; then
diff --git a/src/mod/compress.mod/configure b/src/mod/compress.mod/configure
--- a/src/mod/compress.mod/configure
+++ b/src/mod/compress.mod/configure
@@ -5,16 +5,32 @@
 # Automatically created by src/mod/eggautoconf from `configure.in'
 #
 
-# This tells the code in ../eggmod.sh to search for the file `compress.c'.
+echo "running in eggdrop mode."
+# This tells the code in eggmod.sh to search for the file `compress.c'.
 # That way we can make sure we're started from the correct directory.
 ac_egg_uniquefile=compress.c
-. ../eggmod.sh
+
+# Scan for out source directory
+ac_egg_srcdir=.
+for i in $*; do
+  case "${i}" in
+    --srcdir=*)
+      ac_egg_srcdir=`echo ${i} | sed -e 's/^--srcdir=//'`
+    ;;
+  esac
+done
+if test -r ${ac_egg_srcdir}/../eggmod.sh; then
+	. ${ac_egg_srcdir}/../eggmod.sh
+else
+	echo "$0: error: failed to locate eggmod.sh in ${ac_egg_srcdir}/.." >&2
+	exit 1
+fi
 
 # Standard autoconf commands/tests follow below.
 
 
 echo $ac_n "checking for gzopen in -lz""... $ac_c" 1>&6
-echo "configure:541: checking for gzopen in -lz" >&5
+echo "configure:557: checking for gzopen in -lz" >&5
 ac_lib_var=`echo z'_'gzopen | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -22,7 +38,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lz  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 549 "configure"
+#line 565 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -33,7 +49,7 @@ int main() {
 gzopen()
 ; return 0; }
 EOF
-if { (eval echo configure:560: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:576: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -54,7 +70,7 @@ else
 fi
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:581: checking how to run the C preprocessor" >&5
+echo "configure:597: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -69,13 +85,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 596 "configure"
+#line 612 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:602: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:618: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -86,13 +102,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 613 "configure"
+#line 629 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:619: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:635: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -103,13 +119,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 630 "configure"
+#line 646 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:636: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:652: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -135,17 +151,17 @@ echo "$ac_t""$CPP" 1>&6
 
 ac_safe=`echo "zlib.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for zlib.h""... $ac_c" 1>&6
-echo "configure:662: checking for zlib.h" >&5
+echo "configure:678: checking for zlib.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 667 "configure"
+#line 683 "configure"
 #include "confdefs.h"
 #include <zlib.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:672: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:688: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -194,17 +210,17 @@ for ac_hdr in unistd.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:721: checking for $ac_hdr" >&5
+echo "configure:737: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 726 "configure"
+#line 742 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:731: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:747: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -233,12 +249,12 @@ done
 for ac_func in getpagesize
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:760: checking for $ac_func" >&5
+echo "configure:776: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 765 "configure"
+#line 781 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -261,7 +277,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:788: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:804: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -286,7 +302,7 @@ fi
 done
 
 echo $ac_n "checking for working mmap""... $ac_c" 1>&6
-echo "configure:813: checking for working mmap" >&5
+echo "configure:829: checking for working mmap" >&5
 if eval "test \"`echo '$''{'ac_cv_func_mmap_fixed_mapped'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -294,7 +310,7 @@ else
   ac_cv_func_mmap_fixed_mapped=no
 else
   cat > conftest.$ac_ext <<EOF
-#line 821 "configure"
+#line 837 "configure"
 #include "confdefs.h"
 
 /* Thanks to Mike Haertel and Jim Avera for this test.
@@ -437,7 +453,7 @@ main()
 }
 
 EOF
-if { (eval echo configure:964: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:980: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_func_mmap_fixed_mapped=yes
 else
diff --git a/src/mod/dns.mod/configure b/src/mod/dns.mod/configure
--- a/src/mod/dns.mod/configure
+++ b/src/mod/dns.mod/configure
@@ -5,22 +5,38 @@
 # Automatically created by src/mod/eggautoconf from `configure.in'
 #
 
-# This tells the code in ../eggmod.sh to search for the file `coredns.c'.
+echo "running in eggdrop mode."
+# This tells the code in eggmod.sh to search for the file `coredns.c'.
 # That way we can make sure we're started from the correct directory.
 ac_egg_uniquefile=coredns.c
-. ../eggmod.sh
+
+# Scan for out source directory
+ac_egg_srcdir=.
+for i in $*; do
+  case "${i}" in
+    --srcdir=*)
+      ac_egg_srcdir=`echo ${i} | sed -e 's/^--srcdir=//'`
+    ;;
+  esac
+done
+if test -r ${ac_egg_srcdir}/../eggmod.sh; then
+	. ${ac_egg_srcdir}/../eggmod.sh
+else
+	echo "$0: error: failed to locate eggmod.sh in ${ac_egg_srcdir}/.." >&2
+	exit 1
+fi
 
 # Standard autoconf commands/tests follow below.
 
 
 dns_reslib_avail="true"
 echo $ac_n "checking for res_init""... $ac_c" 1>&6
-echo "configure:542: checking for res_init" >&5
+echo "configure:558: checking for res_init" >&5
 if eval "test \"`echo '$''{'ac_cv_func_res_init'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 547 "configure"
+#line 563 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char res_init(); below.  */
@@ -43,7 +59,7 @@ res_init();
 
 ; return 0; }
 EOF
-if { (eval echo configure:570: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:586: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_res_init=yes"
 else
@@ -61,7 +77,7 @@ if eval "test \"`echo '$ac_cv_func_'res_init`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for res_init in -lresolv""... $ac_c" 1>&6
-echo "configure:588: checking for res_init in -lresolv" >&5
+echo "configure:604: checking for res_init in -lresolv" >&5
 ac_lib_var=`echo resolv'_'res_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -69,7 +85,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lresolv  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 596 "configure"
+#line 612 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -80,7 +96,7 @@ int main() {
 res_init()
 ; return 0; }
 EOF
-if { (eval echo configure:607: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:623: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -99,7 +115,7 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for res_init in -lbind""... $ac_c" 1>&6
-echo "configure:626: checking for res_init in -lbind" >&5
+echo "configure:642: checking for res_init in -lbind" >&5
 ac_lib_var=`echo bind'_'res_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -107,7 +123,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lbind  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 634 "configure"
+#line 650 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -118,7 +134,7 @@ int main() {
 res_init()
 ; return 0; }
 EOF
-if { (eval echo configure:645: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:661: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -144,12 +160,12 @@ fi
 
 fi
 echo $ac_n "checking for res_mkquery""... $ac_c" 1>&6
-echo "configure:671: checking for res_mkquery" >&5
+echo "configure:687: checking for res_mkquery" >&5
 if eval "test \"`echo '$''{'ac_cv_func_res_mkquery'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 676 "configure"
+#line 692 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char res_mkquery(); below.  */
@@ -172,7 +188,7 @@ res_mkquery();
 
 ; return 0; }
 EOF
-if { (eval echo configure:699: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:715: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_res_mkquery=yes"
 else
@@ -190,7 +206,7 @@ if eval "test \"`echo '$ac_cv_func_'res_mkquery`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for res_mkquery in -lresolv""... $ac_c" 1>&6
-echo "configure:717: checking for res_mkquery in -lresolv" >&5
+echo "configure:733: checking for res_mkquery in -lresolv" >&5
 ac_lib_var=`echo resolv'_'res_mkquery | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -198,7 +214,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lresolv  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 725 "configure"
+#line 741 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -209,7 +225,7 @@ int main() {
 res_mkquery()
 ; return 0; }
 EOF
-if { (eval echo configure:736: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:752: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -231,7 +247,7 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for res_mkquery in -lbind""... $ac_c" 1>&6
-echo "configure:758: checking for res_mkquery in -lbind" >&5
+echo "configure:774: checking for res_mkquery in -lbind" >&5
 ac_lib_var=`echo bind'_'res_mkquery | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -239,7 +255,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lbind  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 766 "configure"
+#line 782 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -250,7 +266,7 @@ int main() {
 res_mkquery()
 ; return 0; }
 EOF
-if { (eval echo configure:777: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:793: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
