Update releaseprep to use git for ChangeLog

diff --git a/misc/releaseprep b/misc/releaseprep
--- a/misc/releaseprep
+++ b/misc/releaseprep
@@ -34,14 +34,18 @@ show_usage() {
 	exit 1
 }
 
+git_log() {
+	git log --no-merges --pretty=format:"%w(75)%H %n Committed %ai by %an %n %s %n %b%n" > ChangeLog
+}
+
 regenerate_changelog() {
-	cvs2cl=`which cvs2cl`
-	if test "x${cvs2cl}" = "x"; then
-		echo "Error: Could not locate \`cvs2cl' program."
+	git=`which git`
+	if test "x${git}" = "x"; then
+		echo "Error: Could not locate \`git' program."
 		exit 1
 	fi
-	if ! $cvs2cl; then
-		echo "Error while attempting to run \`cvs2cl' program."
+	if ! git_log; then
+		echo "Error while attempting to run \`git log' program."
 		exit 1
 	fi
 	if test -f ChangeLog; then
@@ -70,7 +74,7 @@ change_default_make() {
 fix_patch_h() {
 	if test $do_rc -eq 1; then
 		misc/addpatch RC${rc_number} >/dev/null
-		cat src/patch.h | sed 's/^patch.*CVS.*CVS version \*\//patch("PRE-RELEASE");           \/* RC version *\//g' > src/patch.h_
+		cat src/patch.h | sed 's/^patch.*Git.*Git version \*\//patch("PRE-RELEASE");           \/* RC version *\//g' > src/patch.h_
 	else
 		cat src/patch.h | sed 's/^patch.*/\/* PATCH GOES HERE *\//g' > src/patch.h_
 	fi
@@ -125,14 +129,15 @@ fix_patch_h
 echo " done."
 
 # Remove CVS dirs.
+# Let's remove this in 1.8.1 -Geo
 echo -n "Removing CVS and autom4te.cache directories..."
 find ./ -type d -name "autom4te.cache" -print | xargs rm -rf
 find ./ -type d -name "CVS" -print | xargs rm -rf
 echo " done."
 
-# Remove .cvsignores.
-echo -n "Removing .cvsignore files..."
-find ./ -name ".cvsignore" -print | xargs rm -f
+# Remove .gitignores.
+echo -n "Removing .gitignore files..."
+find ./ -name ".gitignore" -print | xargs rm -f
 echo " done."
 
 # Remove doc/web_docs/ and doc/html/chat/
