Modified releaseprep script to run cvs2cl so we will (hopefully) have an up-to-date ChangeLog file before each release.

diff --git a/misc/releaseprep b/misc/releaseprep
--- a/misc/releaseprep
+++ b/misc/releaseprep
@@ -23,7 +23,7 @@
 # configuration script generated by Autoconf, you may include it under
 # the same distribution terms that you use for the rest of that program.
 #
-# $Id: releaseprep,v 1.16 2008/02/16 21:41:02 guppy Exp $
+# $Id: releaseprep,v 1.17 2008/06/17 10:49:01 tothwolf Exp $
 
 show_usage() {
 	echo "Usage: `basename $0` [-h|-r <#>]"
@@ -34,6 +34,31 @@ show_usage() {
 	echo "  -h, --help - Print this help and exit."
 	echo "  -r, --rc   - Prepare to release Release Candidate '#'."
 	exit 1
+}
+
+regenerate_changelog() {
+	cvs2cl=`which cvs2cl`
+	if test "x${cvs2cl}" = "x"; then
+		echo "Error: Could not locate \`cvs2cl' program."
+		exit 1
+	fi
+	if ! $cvs2cl; then
+		echo "Error while attempting to run \`cvs2cl' program."
+		exit 1
+	fi
+	if test -f ChangeLog; then
+		if test -s ChangeLog; then
+			if test -f ChangeLog.bak; then
+				rm -f ChangeLog.bak
+			fi
+		else
+			echo "Error: Generated ChangeLog file is empty."
+			exit 1
+		fi
+	else
+		echo "Error: No ChangeLog file found."
+		exit 1
+	fi
 }
 
 change_default_make() {
@@ -84,6 +109,12 @@ if test ! -f src/main.c; then
 	echo "You are not in the Eggdrop root directory."
 	exit 1
 fi
+
+
+# Regenerate ChangeLog file before doing anything else...
+echo "Regenerating ChangeLog file..."
+regenerate_changelog
+echo ""
 
 # Change default make from "debug" to "eggdrop"...
 echo -n "Changing default make..."
