Commit, Tag, Push final release version

diff --git a/misc/releaseprep b/misc/releaseprep
--- a/misc/releaseprep
+++ b/misc/releaseprep
@@ -24,10 +24,9 @@
 # the same distribution terms that you use for the rest of that program.
 
 show_usage() {
-	echo "Usage: `basename $0` [-h|-r <#>]"
+	echo "Usage: `basename $0` [-h|-r <#>] lastVer"
 	echo ""
-	echo "  patchname  - Name of last patch added."
-	echo "  unixtime   - Some unixtime number or 'now'. Default is 'now'."
+        echo "  lastVer    - git tag of last version (v1.6.21 or v1.8.0 for example)"
 	echo ""
 	echo "  -h, --help - Print this help and exit."
 	echo "  -r, --rc   - Prepare to release Release Candidate '#'."
@@ -35,7 +34,7 @@ show_usage() {
 }
 
 git_log() {
-	git log --name-only --no-merges --pretty=format:"- - - - - - - - - - - - - - - %n%w(75)Commit %h (%ai) by %aN %n %s %n %b" > ChangeLog
+	git log $(git rev-list -n 1 $1)..HEAD --name-only --no-merges --pretty=format:"- - - - - - - - - - - - - - - %n%w(75)Commit %h (%ai) by %aN %n %s %n %b" > ChangeLog
 }
 
 regenerate_changelog() {
@@ -44,7 +43,7 @@ regenerate_changelog() {
 		echo "Error: Could not locate \`git' program."
 		exit 1
 	fi
-	if ! git_log; then
+	if ! git_log $1; then
 		echo "Error while attempting to run \`git log' program."
 		exit 1
 	fi
@@ -94,6 +93,11 @@ all:
 _EOF
 }
 
+if [ $# -eq 0 ]; then
+  echo "No args specified, use -h to view help"
+  exit 1
+fi
+
 if test "x${1}" = "x-h" || test "x${1}" = "x--help"; then
 	show_usage
 fi
@@ -107,6 +111,12 @@ if test "x${1}" = "x-r" || test "x${1}" = "x--rc"; then
 	rc_number=$2
 fi
 
+for LASTVER in $@; do :; done
+if ! git rev-parse $LASTVER > /dev/null 2>&1; then
+  echo "No git version tag found: $LASTVER"
+  exit 1
+fi
+
 if test ! -f src/main.c; then
 	echo "You are not in the Eggdrop root directory."
 	exit 1
@@ -115,7 +125,7 @@ fi
 
 # Regenerate ChangeLog file before doing anything else...
 echo "Regenerating ChangeLog file..."
-regenerate_changelog
+regenerate_changelog $LASTVER
 echo ""
 
 # Change default make from "debug" to "eggdrop"...
@@ -166,3 +176,23 @@ echo " done."
 echo Current patch: `misc/addpatch -s`
 echo "Complete."
 echo ""
+
+echo "This next step will commit, tag, and push to GitHub."
+echo "IT IS NOT REVERSIBLE!"
+echo "This is, like, the real deal."
+echo "Are you sure you want to do this? [y/N]: "
+read PUSH
+if [ $PUSH == "y" ]; then
+  echo "Enter release tag (vX.Y.Z[.RC0] format): "
+  read RLS
+  MAJMIN=echo RLS|cut -d'.' -f1,2|sed 's/^v//'
+  git add *
+  git commit -m "Final release - $RLS"
+  git checkout -B stable/$MAJMIN
+  git merge develop
+  git tag $RLS
+  git push origin stable/$MAJMIN
+else
+  echo "Aborting. Coward."
+  exit 0
+fi
