Update copyright year and improve script formatting
Add a way for users to name their systemd unit, to avoid accidental overwrite of existing units.

diff --git a/scripts/autobotchk b/scripts/autobotchk
--- a/scripts/autobotchk
+++ b/scripts/autobotchk
@@ -1,7 +1,7 @@
 #! /bin/sh
 #
 # Copyright (C) 1999-2003 Jeff Fisher (guppy@eggheads.org)
-# Copyright (C) 2004-2025 Eggheads Development Team
+# Copyright (C) 2004-2026 Eggheads Development Team
 #
 # systemd formatting contributed by PeGaSuS
 #
@@ -22,39 +22,39 @@
 # This trick is borrowed from Tothwolf's Wolfpack \
 # Check for working 'grep -E' before using 'egrep' \
 if echo a | (grep -E '(a|b)') >/dev/null 2>&1; \
-then \
+  then \
   egrep="grep -E"; \
-else \
+  else \
   egrep=egrep; \
-fi; \
-# Search for tclsh[0-9].[0-9] in each valid dir in PATH \
-for dir in $(echo $PATH | sed 's/:/ /g'); \
-do \
+  fi; \
+  # Search for tclsh[0-9].[0-9] in each valid dir in PATH \
+  for dir in $(echo $PATH | sed 's/:/ /g'); \
+  do \
   if test -d $dir; \
   then \
-    files=$(/bin/ls $dir | $egrep '^tclsh[0-9]\.[0-9]$'); \
-    if test "$files" != ""; \
-    then \
-      versions="${versions:+$versions }$(echo $files | sed 's/tclsh//g')"; \
-    fi; \
+  files=$(/bin/ls $dir | $egrep '^tclsh[0-9]\.[0-9]$'); \
+  if test "$files" != ""; \
+  then \
+  versions="${versions:+$versions }$(echo $files | sed 's/tclsh//g')"; \
   fi; \
-done; \
-for ver in $versions; \
-do \
+  fi; \
+  done; \
+  for ver in $versions; \
+  do \
   tmpver=$(echo $ver | sed 's/\.//g'); \
   if test "$lasttmpver" != ""; \
   then \
-    if test "$tmpver" -gt "$lasttmpver"; \
-    then \
-      lastver=$ver; \
-      lasttmpver=$tmpver; \
-    fi; \
-  else \
-    lastver=$ver; \
-    lasttmpver=$tmpver; \
+  if test "$tmpver" -gt "$lasttmpver"; \
+  then \
+  lastver=$ver; \
+  lasttmpver=$tmpver; \
   fi; \
-done; \
-exec tclsh$lastver "$0" ${1+"$@"}
+  else \
+  lastver=$ver; \
+  lasttmpver=$tmpver; \
+  fi; \
+  done; \
+  exec tclsh$lastver "$0" ${1+"$@"}
 #
 # AutoBotchk - An eggdrop utility to autogenerate botchk/crontab entries
 #
@@ -246,83 +246,92 @@ foreach config $confs {
   puts " done"
 }
 
- if {![info exists {botnet-nick}] && [info exists nick]} {
+if {![info exists {botnet-nick}] && [info exists nick]} {
   puts "  Defaulting \$botnet-nick to \"$nick\""
   set botnet-nick $nick
- }
- if {![info exists {botnet-nick}] || ![info exists userfile]} {
+}
+if {![info exists {botnet-nick}] || ![info exists userfile]} {
   puts "  *** ERROR: could not find either \$userfile or \$botnet-nick"
   puts ""
   puts "  Are you sure this is a valid eggdrop config file?"
   puts ""
   exit
- }
- catch {exec "$dir/$binary" -v} execres
- if {![regexp {handlen=([0-9]+)} "$execres" -> handlen]} {
+}
+catch {exec "$dir/$binary" -v} execres
+if {![regexp {handlen=([0-9]+)} "$execres" -> handlen]} {
   puts "  Could not find handlen used, defaulting to 32."
   # len 32 means up to index 31
   set handlen 31
- } else {
+} else {
   set handlen [expr $handlen - 1]
- }
- set nick [string range [subst -nocommands $nick] 0 $handlen]
- set botnet-nick [string range [subst -nocommands ${botnet-nick}] 0 $handlen]
+}
+set nick [string range [subst -nocommands $nick] 0 $handlen]
+set botnet-nick [string range [subst -nocommands ${botnet-nick}] 0 $handlen]
 
 ### systemd stuff
 if {$systemd} {
- puts "Enabling user lingering..."
- if {[catch {exec loginctl enable-linger} res]} {
-  puts "Oops, something went wrong. Is systemd running on this system?"
-  exit
- }
- puts "Creating systemd directory..."
- catch {file mkdir "$::env(HOME)/.config/systemd/user" } res
- if {[catch {open "$::env(HOME)/.config/systemd/user/${botnet-nick}.service" w} fd]} {
-  puts "  *** ERROR: unable to open '${botnet-nick}.service' for writing"
-  puts ""
-  exit
- }
- puts $fd "### Eggdrop systemd unit, generated by autosystemd"
- puts $fd ""
- puts $fd "\[Unit\]"
- puts $fd "Description=${botnet-nick} (Eggdrop)"
- puts $fd "After=default.target"
- puts $fd ""
- puts $fd "\[Service\]"
- puts $fd "WorkingDirectory=${dir}"
- puts $fd "ExecStart=${dir}/eggdrop ${config}"
- puts $fd "ExecReload=${kill} -s HUP \$MAINPID"
- puts $fd "Type=forking"
- puts $fd "Restart=on-abnormal"
- puts $fd ""
- puts $fd "\[Install\]"
- puts $fd "WantedBy=default.target"
- close $fd
+  # Prompt for custom unit name
+  puts -nonewline "Enter systemd unit name (without .service) \[default: ${botnet-nick}\]: "
+  flush stdout
+  set input [string trim [gets stdin]]
+  if {$input ne ""} {
+    set unitname $input
+  } else {
+    set unitname ${botnet-nick}
+  }
+  puts "Enabling user lingering..."
+  if {[catch {exec loginctl enable-linger} res]} {
+    puts "Oops, something went wrong. Is systemd running on this system?"
+    exit
+  }
+  puts "Creating systemd directory..."
+  catch {file mkdir "$::env(HOME)/.config/systemd/user" } res
+  if {[catch {open "$::env(HOME)/.config/systemd/user/${unitname}.service" w} fd]} {
+    puts "  *** ERROR: unable to open '${unitname}.service' for writing"
+    puts ""
+    exit
+  }
+  puts $fd "### Eggdrop systemd unit, generated by autosystemd"
+  puts $fd ""
+  puts $fd "\[Unit\]"
+  puts $fd "Description=${botnet-nick} (Eggdrop)"
+  puts $fd "After=default.target"
+  puts $fd ""
+  puts $fd "\[Service\]"
+  puts $fd "WorkingDirectory=${dir}"
+  puts $fd "ExecStart=${dir}/eggdrop ${config}"
+  puts $fd "ExecReload=${kill} -s HUP \$MAINPID"
+  puts $fd "Type=forking"
+  puts $fd "Restart=on-abnormal"
+  puts $fd ""
+  puts $fd "\[Install\]"
+  puts $fd "WantedBy=default.target"
+  close $fd
 
- catch {exec systemctl --user enable ${botnet-nick}.service} res
- puts $res
- puts "systemd job successfully installed as '${botnet-nick}.service'."
- puts "* Use 'systemctl --user <start|stop|restart|reload|enable|disable> ${botnet-nick}.service' to control your Eggdrop"
- puts "Starting Eggdrop..."
- if {[catch {exec systemctl --user start ${botnet-nick}.service} res]} {
-  puts "ERROR: Eggdrop did not start."
+  catch {exec systemctl --user enable ${unitname}.service} res
   puts $res
- } else {
-  puts "Success."
- }
- exit
+  puts "systemd job successfully installed as '${unitname}.service'."
+  puts "* Use 'systemctl --user <start|stop|restart|reload|enable|disable> ${unitname}.service' to control your Eggdrop"
+  puts "Starting Eggdrop..."
+  if {[catch {exec systemctl --user start ${unitname}.service} res]} {
+    puts "ERROR: Eggdrop did not start."
+    puts $res
+  } else {
+    puts "Success."
+  }
+  exit
 }
 
 
 if {![info exists pidfile]} {
- puts "  Defaulting \$pidfile to \"pid.${botnet-nick}\""
- set pidfile "pid.${botnet-nick}"
+  puts "  Defaulting \$pidfile to \"pid.${botnet-nick}\""
+  set pidfile "pid.${botnet-nick}"
 }
 set pidfile [subst -nocommands $pidfile]
 if {[catch {open $dir/${botnet-nick}.botchk w} fd]} {
- puts "  *** ERROR: unable to open '${botnet-nick}.botchk' for writing"
- puts ""
- exit
+  puts "  *** ERROR: unable to open '${botnet-nick}.botchk' for writing"
+  puts ""
+  exit
 }
 puts $fd "#! /bin/sh
 #
@@ -355,74 +364,74 @@ cd \$botdir
 # is there a pid file?
 if test -r \$pidfile
 then
-  # there is a pid file -- is it current?
-  botpid=`cat \$pidfile`
-  if `kill -CHLD \$botpid >/dev/null 2>&1`
-  then
-    # it's still going -- back out quietly
-    exit 0
-  fi
-  echo \"\"
-  echo \"Stale \$pidfile file, erasing...\"
-  rm -f \$pidfile
+# there is a pid file -- is it current?
+botpid=`cat \$pidfile`
+if `kill -CHLD \$botpid >/dev/null 2>&1`
+then
+# it's still going -- back out quietly
+exit 0
+fi
+echo \"\"
+echo \"Stale \$pidfile file, erasing...\"
+rm -f \$pidfile
 fi
 
 if test -r CANTSTART.\$botname
 then
-  if test -r \$userfile || test -r \$userfile~new || test -r \$userfile~bak
-  then
-    echo \"\"
-    echo \"Userfile found, removing check file 'CANTSTART.\$botname'...\"
-    rm -f CANTSTART.\$botname
-  fi
+if test -r \$userfile || test -r \$userfile~new || test -r \$userfile~bak
+then
+echo \"\"
+echo \"Userfile found, removing check file 'CANTSTART.\$botname'...\"
+rm -f CANTSTART.\$botname
+fi
 fi
 
 # test if we have run botchk previously and didn't find a userfile
 if test ! -f CANTSTART.\$botname
 then
-  echo \"\"
-  echo \"Couldn't find bot '\$botname' running, reloading...\"
-  echo \"\"
-  # check for userfile and reload bot if found
-  if test -r \$userfile
-  then
-    # It's there, load the bot
-    ./\$botscript
-    exit 0
-  else
-    if test -r \$userfile~new
-    then
-      # Bot f*@!ed up while saving the userfile last time.  Move it over.
-      echo \"Userfile missing.  Using last saved userfile...\"
-      mv -f \$userfile~new \$userfile
-      ./\$botscript
-      exit 0
-    else
-      if test -r \$userfile~bak
-      then
-        # Userfile is missing, use backup userfile.
-        echo \"Userfile missing.  Using backup userfile...\"
-        cp -f \$userfile~bak \$userfile
-        ./\$botscript
-        exit 0
-      else
-        # Well, nothing to work with...
-        echo \"No userfile.  Could not reload the bot...\"
-        echo \"no userfile\" > CANTSTART.\$botname
-        exit 1
-      fi
-    fi
-  fi
+echo \"\"
+echo \"Couldn't find bot '\$botname' running, reloading...\"
+echo \"\"
+# check for userfile and reload bot if found
+if test -r \$userfile
+then
+# It's there, load the bot
+./\$botscript
+exit 0
+else
+if test -r \$userfile~new
+then
+# Bot f*@!ed up while saving the userfile last time.  Move it over.
+echo \"Userfile missing.  Using last saved userfile...\"
+mv -f \$userfile~new \$userfile
+./\$botscript
+exit 0
+else
+if test -r \$userfile~bak
+then
+# Userfile is missing, use backup userfile.
+echo \"Userfile missing.  Using backup userfile...\"
+cp -f \$userfile~bak \$userfile
+./\$botscript
+exit 0
+else
+# Well, nothing to work with...
+echo \"No userfile.  Could not reload the bot...\"
+echo \"no userfile\" > CANTSTART.\$botname
+exit 1
+fi
+fi
+fi
 fi
 
 exit 0
- "
+"
 close $fd
 puts "Wrote '${botnet-nick}.botchk' successfully ([file size $dir/${botnet-nick}.botchk] bytes)"
 if {[catch {exec chmod u+x $dir/${botnet-nick}.botchk} 0]} {
- puts "  *** ERROR: unable to 'chmod u+x' the output file"
- puts ""
- exit
+  puts "  *** ERROR: unable to 'chmod u+x' the output file"
+  puts ""
+  exit
 }
 puts -nonewline "Scanning crontab entries ... "
 
@@ -436,7 +445,7 @@ if {$email} {
 
 if {[catch {exec crontab -l > $tmp} error ]} {
   if {![string match "*no*cron*" [string tolower $error]] &&
-      ![string match "*can't open*" [string tolower $error]]} {
+    ![string match "*can't open*" [string tolower $error]]} {
     catch {file delete -force $tmp} 0
     puts "error: unable to get crontab listing"
     puts ""
@@ -451,7 +460,7 @@ set fd [open $tmp r]
 while {![eof $fd]} {
   set z [gets $fd]
   if {[string match "*$dir/${cronbotchk}*" $z] ||
-      [string match "*$dir//${cronbotchk}*" $z]} {
+  [string match "*$dir//${cronbotchk}*" $z]} {
     puts "found an existing entry, we're done now"
     puts ""
     exit
