patches and more patches

diff --git a/scripts/botchk b/scripts/botchk
--- a/scripts/botchk
+++ b/scripts/botchk
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# new botchk  (for eggdrop 1.1)
+# new botchk  (for eggdrop 1.1+)
 #
 # This is a script suitable for use in a crontab.  It checks to make sure
 # your bot is running.  YOU NEED A SEPARATE CRON JOB FOR EACH BOT.  If your
@@ -31,41 +31,68 @@ userfile="Doofy.user"
 ########## you probably don't need to change anything below here ##########
 
 cd $botdir
-if test -r pid.$botname; then
+
+# is there a pid file?
+if test -r pid.$botname
+then
   # there is a pid file -- is it current?
   botpid=`cat pid.$botname`
-  if `kill -CHLD $botpid >/dev/null 2>&1`; then
-    # it's still going
-    # back out quietly
+  if `kill -CHLD $botpid >/dev/null 2>&1`
+  then
+    # it's still going -- back out quietly
     exit 0
   fi
   echo ""
-  echo "Stale pid.$botname file (erasing it)"
+  echo "Stale pid.$botname file, erasing..."
   rm -f pid.$botname
 fi
-echo ""
-echo "Couldn't find the bot running.  Reloading it..."
-echo ""
-# Check for userfile first
-if test -r $userfile; then
-   # It's there, load the bot
-  ./$botscript
-  exit 0
+
+if test -r CANTSTART.$botname
+then
+  if test -r $userfile || test -r $userfile~new || test -r $userfile~bak
+  then
+    echo ""
+    echo "Userfile found, removing check file 'CANTSTART.$botname'..."
+    rm -f CANTSTART.$botname
+  fi
 fi
-if test -r $userfile~new; then
-   # Bot f*@!ed up while saving the userfile last time.  Move it over.
-   echo "Userfile missing.  Using last saved userfile..."
-   mv $userfile~new $userfile
-  ./$botscript
-  exit 0
+
+# test if we have run botchk previously and didn't find a userfile
+if test ! -f CANTSTART.$botname
+then
+  echo ""
+  echo "Couldn't find bot '$botname' running, reloading..."
+  echo ""
+  # check for userfile and reload bot if found
+  if test -r $userfile
+  then
+    # It's there, load the bot
+    ./$botscript
+    exit 0
+  else
+    if test -r $userfile~new
+    then
+      # Bot f*@!ed up while saving the userfile last time.  Move it over.
+      echo "Userfile missing.  Using last saved userfile..."
+      mv -f $userfile~new $userfile
+      ./$botscript
+      exit 0
+    else
+      if test -r $userfile~bak
+      then
+        # Userfile is missing, use backup userfile.
+        echo "Userfile missing.  Using backup userfile..."
+        cp -f $userfile~bak $userfile
+        ./$botscript
+        exit 0
+      else
+        # Well, nothing to work with...
+        echo "No userfile.  Could not reload the bot..."
+        echo "no userfile" > CANTSTART.$botname
+        exit 1
+      fi
+    fi
+  fi
 fi
-if test -r $userfile~bak; then
-   # Userfile is missing, use backup userfile.
-   echo "Userfile missing.  Using backup userfile..."
-   cp $userfile~bak $userfile
-  ./$botscript
-  exit 0
-fi
-# Well, nothing to work with...
-echo "No userfile.  Could not reload the bot.."
+
 exit 0
